name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: cachix/cachix-action@v14
      with:
        name: famisoft
        skipPush: true
    - run: nix build -L --show-trace
